#!/usr/bin/env bash
# Installing Nginx on Ubuntu
# Nginx is listening on port 80
# The GET request should return a page containing "Holberton School"

# Update and upgrade the system
sudo apt-get update
sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Create the HTML directory if it doesn't exist
sudo mkdir -p /var/www/html

# Create the index.html file and add the required content
echo "Holberton School" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
